### ISSUE TITLE
Can't log in to dev box

### ISSUE THREAD

**Issue by NOwen1stNut** [zacbraddy/scout-waiting-list#11]
Expected Behaviour:

Go to the prod box https://scout-waiting-list-dev.web.app/admin
Hit login with google
select nowen@1stnuthallscouts.org.uk in pop up auth window
window closes
Admin console should load

Actual Behaviour

Go to the prod box https://scout-waiting-list-dev.web.app/admin
Hit login with google
select nowen@1stnuthallscouts.org.uk in pop up auth window
window closes
Page shows loading...

![image](https://user-images.githubusercontent.com/60623783/73682222-d84b6280-46b7-11ea-9389-76b66ac40bcc.png)

**Comment by zacbraddy** [comment]
Mate your bug logging skill are legit AF

Should be fixed on both environments. Give it a test and let me know via either here or email and we can close this bug.

**Comment by NOwen1stNut** [comment]
Confirmed resolved. Can log onto both prod and dev without issues.
