### ISSUE TITLE
No "Add" option in Admin for Production

### ISSUE THREAD

**Issue by thisisthetechie** [zacbraddy/scout-waiting-list#12]
![image](https://user-images.githubusercontent.com/26260542/73747537-8d7d2980-474f-11ea-94ee-3b08c9d70209.png)

I don't seem to have the option to "Add" a row, only "Edit" a row? This affects both DEV and PROD.

**Comment by zacbraddy** [comment]
I understand it's not the greatest UX in the world but that edit button in the bottom left corner refers to going into "Edit mode" which will allow you to Add, edit or delete rows. Outside of this edit mode is where you can drag and reorder the rows.

Put simply, click on the button in the bottom right corner and you'll see the Add button appear. Give it a crack and if it works for you then go ahead and close this issue ;)

**Comment by thisisthetechie** [comment]
Yup, that'll do it :)
